### ISSUE TITLE
Remove generatePort() and use default MongoDB port

### ISSUE THREAD

**Issue by NicolasRitouet** [deployd/deployd-cli#20]
Currently, when the user doesn't specify the mongodb port, deployd will pick a random one (due to legacy reason).

Instead, we'd like to use the default MongoDB port (27017).

# Todo
- The method `generatePort` is not needed anymore (https://github.com/deployd/deployd-cli/blob/master/lib/cli/start.js#L176-L179)
- if a port is specified as param (https://github.com/deployd/deployd-cli/blob/master/lib/cli/start.js#L45), use it
- if not, use the default port (`27017`): https://github.com/deployd/deployd-cli/blob/master/lib/cli/start.js#L34

**Comment by Kapnobatai3434** [comment]
Hi, I'd like to tackle that one.

**Comment by NicolasRitouet** [comment]
Great, go ahead. 👍

Le sam. 29 juil. 2017 à 13:20, John Scetinin <notifications@github.com> a
écrit :
